### ISSUE TITLE
Pull not possible anymore

### ISSUE THREAD

**Issue by phrutos** [six7/figma-tokens-example-multi#11]
Hello, 

My current repo was pulling normal, until recently. Now, I'm getting an error at the **stefanzweifel** build. It says "Write access not granted", but all repo access is granted in my personal access token. I created new ones, and I am getting the same problem. I am traveling, so my network changes constantly, but I have a VPN. 

Last week I had this issue on a different repo, and the issue went away 24hrs later. I am wondering if there's anything to do with the new Figma Tokens update. 

Thanks!

Log:
INPUT_PUSH_OPTIONS: 
remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/phrutos/myrepo/': The requested URL returned error: 403
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5) {
  code: 128
}
Error: Invalid status code: 128
    at ChildProcess.<anonymous> (/home/runner/work/_actions/stefanzweifel/git-auto-commit-action/v4/index.js:17:19)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1022:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)

**Comment by phrutos** [comment]
Something had changed the repo's actions read/write permissions. I went to the repo settings > actions > Workflow permissions and selected **Read and write permissions**. Strange it was working fine before.
